Handle both null and undefined
In using this plugin, a model attribute was sorting on was null which caused the library to throw  this error: 

TypeError: Cannot read property 'toString' of null

So, instead of explicitly checking for undefined (void 0) , it's probably best to check for anything that falsey which would include null, undefined and empty string.